=== Zekom/xerces/design/xml/schedule.dtd
<?xml encoding='US-ASCII'?>
<!-- $Id$ -->
<!ENTITY % person SYSTEM 'person.dtd'>
%person;
<!ELEMENT schedule (person*,milestone*)>
<!ATTLIST schedule date CDATA #REQUIRED>
<!ELEMENT milestone (title,depends*,goal*)>
<!ATTLIST milestone id      ID     #REQUIRED
                    date    CDATA  #IMPLIED
		    owner   IDREF  #IMPLIED>
<!ELEMENT depends EMPTY>
<!ATTLIST depends idref IDREF #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT goal (#PCDATA)>
<!ATTLIST goal owner IDREF #IMPLIED
               status (working|verify|done) 'working'>

=== Zekom/xerces/design/xml/schedule.xml
<?xml version='1.0' encoding='US-ASCII'?>
<!-- $Id$ -->
<!DOCTYPE schedule SYSTEM 'schedule.dtd' [
<!ENTITY people SYSTEM 'people.ent'>
]>
<schedule date='$Date$'>
 &people;
 <milestone id='M1' date='Friday, 29 Sep 2000'>
  <title>Parser without DTD support</title>
  <goal owner='andyc'>
   Document design based on Xerces community feedback.
  </goal>
  <goal owner='ericye' status='verify'>
   Support classes. (XMLString, XMLStringBuffer,
   XMLChar, EncodingMap, SymbolTable, QName)
  </goal>
  <goal owner='jeffreyr'>
   Basic entity managment. (XMLEntityManager, XMLEntityScanner)
  </goal>
  <goal owner='ericye'>
   Basic error handling. (XMLErrorReporter, some MessageFormatter)
  </goal>
  <goal owner='andyc'>
   Parsing of elements and attributes using internal interface.
   (XMLAttributes, XMLDocumentScanner)
  </goal>
  <goal owner='lehors'>
   Implement a SAX2 parser from internal callbacks.
   (XMLParser, XMLDocumentParser, SAXParser)
  </goal>
 </milestone>
 <milestone id='M2'>
  <depends idref='M1'/>
  <title>Parser with DTD scanning without validation</title>
  <!-- REVISIT: re-group
  <goal>CachingParserPool (supporting GrammarPool)</goal>
  <goal>XMLDTDScanner</goal>
  <goal>XMLGrammarParser/DTDParser</goal>
  <goal>GrammarPool</goal>
  <goal>Grammar/DTDGrammar</goal>
  <goal>XMLElementDecl</goal>
  <goal>XMLAttributeDecl</goal>
  <goal>XMLSimpleType</goal>
  <goal>XMLEntityDecl</goal>
  <goal>XMLNotationDecl</goal>
  -->
 </milestone>
 <milestone id='M3'>
  <depends idref='M2'/>
  <title>Parser with DTD scanning + datatypes validation</title>
  <!-- REVISIT: re-group
  <goal>XMLValidator</goal>
  <goal>DatatypeValidatorFactoryImpl</goal>
  <goal>AbstractDatatypeValidator</goal>
  <goal>StringDatatypeValidator</goal>
  <goal>InvalidDatatypeFacetException</goal>
  <goal>InvalidDatatypeValueException</goal>
  -->
 </milestone>
 <milestone id='M4'>
  <depends idref='M3'/>
  <title>Parser with DTD scanning + datatypes and content model validation</title>
  <!-- REVISIT: re-group
  <goal>SimpleContentModel</goal>
  <goal>MixedContentModel</goal>
  <goal>DFAContentModel</goal>
  -->
 </milestone>
 <milestone id='M5'>
  <depends idref='M4'/>
  <title>Parser with DTD scanning and Schema parsing + validation</title>
  <!-- REVISIT: re-group
  <goal>SchemaGrammar</goal>
  <goal>SchemaParser</goal>
  -->
 </milestone>
</schedule>
